name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.86.2+10

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.2"

publish_to: none

dependencies:
  android_external_storage: ^0.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  auto_updater: ^0.1.2
  background_fetch: ^1.0.3
  badges: ^2.0.1
  buffer: ^1.2.0
  carousel_slider: ^4.0.0
  collection: ^1.15.0-nullsafety.4
  community_material_icon: ^5.9.55
  connectivity_plus: ^2.2.0
  convert: ^3.1.1
  crypto: ^3.0.2
  cryptography: ^2.0.5
  d3_force_flutter:
    git: https://github.com/MathGaps/d3-force-flutter.git
  dart_date: ^1.1.1
  dart_git:
    git: https://github.com/GitJournal/dart-git.git
  device_info_plus: ^4.0.0
  dio: ^4.0.6
  dio_smart_retry: ^1.2.0
  dots_indicator: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.0
  fast_immutable_collections: ^8.1.1
  file_picker: ^4.0.2
  filesystem_picker: ^2.0.0-nullsafety.0
  fimber: ^0.6.1
  fixnum: ^1.0.1
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.1
  flutter_displaymode: ^0.4.1
  flutter_email_sender: ^5.0.2
  flutter_emoji: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_login: ^4.0.0
  flutter_markdown: ^0.6.1
  flutter_runtime_env: ^0.0.4
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^0.21.0+1
  flutter_tex_js: ^1.2.15
  font_awesome_flutter: ^10.0.0
  fs_shim: ^2.0.1+2
  function_types: ^0.1.0
  git_bindings:
    git: https://github.com/GitJournal/git_bindings.git
  git_setup:
    path: packages/git_setup
  google_api_availability: ^3.0.1
  google_fonts: ^2.1.0
  grpc: ^3.0.0
  hive: ^2.2.3
  http: ^0.13.1
  icloud_documents_path:
    git: https://github.com/GitJournal/icloud_documents_path.git
  image_picker: ^0.8.4+1
  in_app_purchase: ^3.1.1
  in_app_purchase_android: ^0.2.3+9
  intl: ^0.17.0
  language_picker: ^0.4.1
  launch_review: ^3.0.1
  markdown: ^6.0.1
  meta: ^1.8.0
  mutex: ^3.0.0
  nested: ^1.0.0
  openssh_ed25519:
    git: https://github.com/GitJournal/openssh_ed25519.git
  org_flutter: ^1.4.0
  package_info_plus: ^1.0.4
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.13.0
  protobuf: ^2.0.0
  provider: ^6.0.1
  quick_actions: ^0.6.0+3
  quiver: ^3.2.1
  recase: ^4.0.0
  receive_sharing_intent: ^1.4.5
  sentry_flutter: ^6.6.1
  share_plus: ^2.1.4
  shared_preferences: ^2.0.5
  sprintf: ^6.0.0
  stack_trace: ^1.10.0
  synchronized: ^3.0.0
  table_calendar: ^3.0.3
  time: ^2.0.0
  timeago: ^3.1.0
  timeline_tile: ^2.0.0
  tuple: ^2.0.1
  universal_io: ^2.0.4
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  yaml: ^3.1.0
  yaml_serializer: ^0.0.12

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.1.0
  dart_code_metrics: ^4.10.1
  flutter_launcher_icons:
    git: https://github.com/dirkbo/flutter_launcher_icons
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  junitreport: ^2.0.2
  process_run: ^0.12.3+2
  test: ^1.16.5
  widgetbook: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true
  macos: true
  windows: false
  linux: false
