name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.31.0+10

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.16.0"
  path: ^1.6.2
  uuid: ^2.0.1
  yaml: ^2.2.0
  firebase_analytics: ^5.0.9
  flutter_crashlytics: ^1.0.0
  shared_preferences: ^0.5.6
  url_launcher: ^5.0.2
  dots_indicator: ^0.0.3
  package_info: ^0.4.0+13
  http: ^0.12.0+1
  badges: ^0.0.6
  share: ^0.6.3+5
  launch_review: ^2.0.0
  device_info: ^0.4.1+4
  flutter_markdown: ^0.3.2
  flutter_email_sender: ^2.0.3
  function_types: ^0.0.2
  auto_size_text: ^2.0.1
  fimber: ^0.3.0
  dynamic_theme: ^1.0.0
  flushbar: ^1.9.0
  flutter_staggered_grid_view: ^0.3.0
  page_transition: "^1.1.5"
  provider: ^3.2.0
  git_bindings: ^0.0.6
  fetch_app_logs: ^0.0.2
  flutter_runtime_env: ^0.0.1
  yaml_serializer: ^0.0.2
  connectivity: ^0.4.6+1

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  screenshots: ^2.1.1
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true
