name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.66.0+10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
    git: https://github.com/GitJournal/intl.git
  path: ^1.6.2
  uuid: ^2.0.1
  yaml: ^2.2.0
  firebase_analytics: ^5.0.11
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  dots_indicator: ^0.0.3
  package_info: ">=0.4.1 <2.0.0"
  http: ^0.12.0+1
  badges: ^1.1.1
  share: ^0.6.3+5
  launch_review: ^2.0.0
  device_info: ">=0.4.2+4 <2.0.0"
  flutter_markdown: ^0.4.2
  flutter_email_sender: ^3.0.1
  function_types: ^0.0.2
  auto_size_text: ^2.0.1
  fimber: ^0.3.0
  dynamic_theme: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  provider: ^3.2.0
  git_bindings: ^0.0.14
  dart_git:
    git: https://github.com/GitJournal/dart_git.git
    #path: /Users/vishesh/src/gitjournal/dart_git
  yaml_serializer: ^0.0.6
  connectivity: ^0.4.6+1
  flutter_emoji: ">= 2.0.0"
  git_url_parse2: ^0.0.1
  synchronized: ^2.2.0
  mutex: ^1.0.3
  steel_crypt: ^1.7.1+1
  font_awesome_flutter: ^8.7.0
  sentry: ">=3.0.0 <4.0.0"
  flutter_sentry: ^0.4.2
  equatable: ^1.1.0
  cached_network_image: ^2.2.0+1
  ssh_key: ^0.5.1
  isolate: ^2.0.3
  flutter_webview_plugin: ^0.3.11
  image_picker: ^0.6.7
  easy_localization: ^2.3.2
  easy_localization_loader: ^0.0.2
  quick_actions: ^0.4.0+5
  receive_sharing_intent: ^1.4.0+2
  in_app_purchase: ^0.3.4+1
  flutter_plugin_android_lifecycle: ^1.0.8 # for fixing the build

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  screenshots: ^2.1.1
  test: ^1.5.1
  import_sorter: ^4.2.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  benchmark_harness: any

dependency_overrides:
  intl:
    git: https://github.com/GitJournal/intl.git
  markdown:
    git: https://github.com/GitJournal/markdown.git

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
    - "assets/langs/en.yaml"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true
