name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.75.1+10

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.0.3"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_git:
    git: https://github.com/GitJournal/dart-git.git
    #path: /Users/vishesh/src/gitjournal/dart-git
  git_bindings:
    #path: /Users/vishesh/src/gitjournal/git_bindings
    git: https://github.com/GitJournal/git_bindings.git
  icloud_documents_path:
    git: https://github.com/GitJournal/icloud_documents_path.git
  auto_size_text: ^2.0.1
  badges: ^1.1.1
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.6+1
  # cryptography: ^1.4.1
  # cryptography_flutter: ^1.0.0
  crypton: ^1.1.3
  device_info: ">=0.4.2+4 <2.0.0"
  dots_indicator: ^0.0.3
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  email_validator: ^1.0.6
  equatable: ^2.0.0
  ext_storage: ^1.0.3
  file_picker: ^3.0.0
  filesystem_picker: ^1.0.3 # for directories
  fimber: ^0.3.0
  firebase_analytics: ^7.1.1
  flutter_cache_manager: ^2.1.2
  flutter_email_sender: ^3.0.1
  flutter_emoji: ">= 2.0.0"
  flutter_markdown: ^0.6.1
  flutter_runtime_env: ^0.0.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.21.0-nullsafety.0
  font_awesome_flutter: ^8.7.0
  function_types: ^0.0.2
  git_url_parse2: ^0.0.1
  google_fonts: ^2.0.0
  http: ^0.13.1
  image_picker: ^0.7.3
  in_app_purchase: ^0.3.4+5
  intl: ^0.17.0
  isolate: ^2.0.3
  launch_review: ^2.0.0
  mutex: ^1.0.3
  package_info: ">=0.4.1 <2.0.0"
  path: ^1.6.2
  permission_handler: ^6.1.1
  photo_view: ^0.10.3
  provider: ^4.3.2+2
  quick_actions: ^0.4.0+10
  receive_sharing_intent: ^1.4.0+2
  sentry: ^4.0.6
  sentry_flutter: ^4.0.6
  share: ^0.6.3+5
  shared_preferences: ^2.0.5
  #ssh_key: ^0.6.0
  stack_trace: ^1.9.6
  synchronized: ^2.2.0
  time: ^1.3.0
  timeago: ^3.0.2
  url_launcher: ^6.0.2
  uuid: ^3.0.2
  yaml: ^3.1.0
  yaml_serializer: ^0.0.9

dev_dependencies:
  #flutter_driver:
  #  sdk: flutter
  flutter_test:
    sdk: flutter
  benchmark_harness: any
  bonsoir: ^0.1.2+2
  flutter_launcher_icons: ^0.9.0
  flutter_webview_plugin: ^0.3.11
  import_sorter: ^4.2.2
  multicast_dns: ^0.2.2
  #screenshots: ^2.1.1
  test: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
    - "assets/langs/en.yaml"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true

import_sorter:
  comments: false
