name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.76.0+10

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.3"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_git:
    git: https://github.com/GitJournal/dart-git.git
    #path: /Users/vishesh/src/gitjournal/dart-git
  git_bindings:
    #path: /Users/vishesh/src/gitjournal/git_bindings
    git: https://github.com/GitJournal/git_bindings.git
  icloud_documents_path:
    git: https://github.com/GitJournal/icloud_documents_path.git
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.0-nullsafety.1
  cached_network_image: ^3.0.0
  connectivity: ^3.0.3
  # cryptography: ^1.4.1
  # cryptography_flutter: ^1.0.0
  crypton: ^2.0.1
  device_info: ^2.0.0
  dots_indicator: ^2.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.0
  ext_storage:
    git: https://github.com/GitJournal/ext_storage.git
  file_picker: ^3.0.1
  filesystem_picker: ^2.0.0-nullsafety.0 # for directories
  fimber: ^0.6.1
  firebase_analytics: ^8.0.0
  flutter_cache_manager: ^3.0.1
  flutter_email_sender: ^5.0.0
  flutter_emoji:
    git: https://github.com/cek-cek/flutter-emoji
  flutter_markdown: ^0.6.1
  flutter_runtime_env: ^0.0.4
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^0.21.0+1
  font_awesome_flutter: ^9.0.0
  function_types: ^0.1.0
  google_fonts: ^2.0.0
  http: ^0.13.1
  image_picker: ^0.7.4
  in_app_purchase: ^0.5.2
  intl: ^0.17.0
  launch_review: ^3.0.1
  mutex: ^3.0.0
  package_info: ^2.0.0
  path: ^1.8.0
  permission_handler: ^6.1.1
  photo_view: ^0.11.1
  provider: ^5.0.0
  quick_actions: ^0.6.0
  receive_sharing_intent: ^1.4.5
  sentry: ^5.0.0
  sentry_flutter: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  #ssh_key: ^0.6.0
  stack_trace: ^1.10.0
  synchronized: ^3.0.0
  time: ^2.0.0
  timeago: ^3.0.2
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  yaml: ^3.1.0
  yaml_serializer: ^0.0.11
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  #flutter_driver:
  #  sdk: flutter
  flutter_test:
    sdk: flutter
  benchmark_harness: ^2.0.0
  bonsoir: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  # flutter_webview_plugin: ^0.3.11
  import_sorter: ^4.4.3
  multicast_dns: ^0.3.0
  #screenshots: ^2.1.1
  test: ^1.16.5

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
    - "assets/langs/en.yaml"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true

import_sorter:
  comments: false
