name: openssh_ed25519
description: Serialize an ed25519 key into the openssh format
version: 1.1.0
homepage: https://github.com/GitJournal/GitJournal/tree/master/packages/openssh_ed25519

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.1
  cryptography: ^2.0.5
  test:
